# MegaWallsFFA Configuration

# Arena settings
arena:
  spawn:
    world: world
    x: 0.5
    y: 101
    z: 0.5
    yaw: 0
    pitch: 0

# Ore settings
ores:
  respawn-timer: 45 # in seconds
  locations:
    - world;10;100;10;1 # world;x;y;z;tier
    - world;20;100;20;2
    - world;30;100;30;3
    - world;40;100;40;4
    - world;50;100;50;5